Repository GOSOPT-CDS-TEAM4/MyRealTripClient, pull requests merged in 2023-05, with the labels that each got.

#3 Feature/reset css setting
  package.json
  src/App.jsx
  src/styles/globalStyle.js
  src/styles/theme.js
  yarn.lock
Labels: init

#24 PR 템플릿 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: init

#48 폴더 추가
  src/components/README.md
  src/mocks/README.md
  src/pages/README.md
  src/utils/README.md
Labels: init

#49 Update README.md
  README.md
Labels: init

#51 ✨ [feat] LandingPage 작업...
  public/assets/icon/img_logo_black.png
  public/assets/icon/img_logo_white.png
  public/assets/icon/menu_white.png
  public/assets/icon/search_white.png
  public/assets/img/img_bangkok.png
  public/assets/img/img_jeju.png
  public/assets/img/img_paris_big.png
  public/assets/img/img_sono.png
  public/assets/img/landing_bangkok.png
  public/assets/img/landing_jeju.png
  public/assets/img/landing_paris.png
  src/App.jsx
  src/components/layout/atom/Flex.jsx
  src/components/layout/atom/Text.jsx
  src/components/layout/main/Landing.jsx
  src/components/layout/molecule/Header.jsx
  src/components/layout/molecule/Layout.jsx
  src/pages/Landing/index.jsx
  src/styles/theme.js
Labels: feature

#57 투어리스트페이지 뷰 구현
  public/assets/icon/ellipse.png
  public/assets/icon/heart_white.png
  src/App.jsx
  src/components/TourListCardSquare.jsx
  src/components/TourListHeaderSection/TourListHeaderSection.jsx
  src/components/TourListHeaderSection/index.js
  src/components/TourListItemSection/TourListItemSection.jsx
  src/components/TourListItemSection/index.js
  src/components/TourListSortNav/TourListSortNav.jsx
  src/components/TourListSortNav/index.js
  src/pages/TourListPage.jsx
Labels: feature

#59 Feature/detail page
  public/assets/icon/line.png
  public/assets/icon/location_gray.png
  public/assets/icon/star_five_black.png
  public/assets/icon/star_five_small.png
  public/assets/img/image 9@2x.png
  public/assets/img/image 9@3x.png
  public/assets/img/img_tour_detail.png
  public/assets/img/img_tour_detail10@2x.png
  public/assets/img/img_tour_detail10@3x.png
  public/assets/img/pocketWifi.png
  src/App.jsx
  src/components/DetailPage/DetailTourAbout/DetailTourAbout.jsx
  src/components/DetailPage/DetailTourAbout/index.js
  src/components/DetailPage/DetailTourCourse/DetailTourCourse.jsx
  src/components/DetailPage/DetailTourCourse/index.js
  src/components/DetailPage/DetailTourDescription/DetailTourDescription.jsx
  src/components/DetailPage/DetailTourDescription/index.js
  src/components/DetailPage/DetailTourGuide/DetailTourGuide.jsx
  src/components/DetailPage/DetailTourGuide/index.js
  src/components/DetailPage/DetailTourImg/DetailTourImg.jsx
  src/components/DetailPage/DetailTourImg/index.js
  src/components/DetailPage/DetailTourMore/DetailTourMore.jsx
  src/components/DetailPage/DetailTourMore/index.js
  src/components/DetailPage/DetailTourNotice/DetailTourNotice.jsx
  src/components/DetailPage/DetailTourNotice/index.js
  src/components/DetailPage/DetailTourReview/DetailTourReview.jsx
  src/components/DetailPage/DetailTourReview/index.js
  src/components/DetailPage/DetailTourTitle/DetailTourTitle.jsx
  src/components/DetailPage/DetailTourTitle/index.js
  src/components/DetailPage/DetailTourTripInfo/DetailTourTripInfo.jsx
  src/components/DetailPage/DetailTourTripInfo/index.js
  src/components/layout/atom/DivideLine.jsx
  src/components/layout/molecule/Button.jsx
  src/pages/DetailTour.jsx
Labels: feature

#60 Feature/landing page
  public/assets/img/img_bangkok.png
  public/assets/img/img_jeju.png
  public/assets/img/img_paris.png
  public/assets/img/landing_bangkok.png
  public/assets/img/landing_jeju.png
  public/assets/img/landing_paris.png
  src/components/layout/atom/Flex.jsx
  src/components/layout/main/Landing.jsx
  src/components/layout/molecule/Header.jsx
  src/components/layout/molecule/Landing/Carousel.jsx
  src/components/layout/molecule/Landing/GoodsSection.jsx
  src/components/layout/molecule/Landing/MainButtonSection.jsx
  src/components/layout/molecule/Landing/MainIconSection.jsx
  src/components/layout/molecule/Landing/TrendPlace.jsx
  src/components/layout/molecule/Landing/TrendPlaceSection.jsx
Labels: feature, refactor

#61 Feature/detail page 리팩토링
  public/assets/icon/ic_appstore.png
  public/assets/icon/ic_facebook.png
  public/assets/icon/ic_facebook@2x.png
  public/assets/icon/ic_facebook@3x.png
  public/assets/icon/ic_googlestore.png
  public/assets/icon/ic_insta.png
  public/assets/icon/ic_insta@2x.png
  public/assets/icon/ic_insta@3x.png
  public/assets/icon/ic_naver.png
  public/assets/icon/ic_naver@2x.png
  public/assets/icon/ic_naver@3x.png
  public/assets/icon/ic_youtube.png
  public/assets/icon/ic_youtube@2x.png
  public/assets/icon/ic_youtube@3x.png
  public/assets/icon/img_logo_isms.png
  src/App.jsx
  src/components/DetailPage/DetailTourAbout/DetailTourAbout.jsx
  src/components/DetailPage/DetailTourCourse/DetailTourCourse.jsx
  src/components/DetailPage/DetailTourDescription/DetailTourDescription.jsx
  src/components/DetailPage/DetailTourGuide/DetailTourGuide.jsx
  src/components/DetailPage/DetailTourImg/DetailTourImg.jsx
  src/components/DetailPage/DetailTourMore/DetailTourMore.jsx
  src/components/DetailPage/DetailTourNotice/DetailTourNotice.jsx
  src/components/DetailPage/DetailTourReview/DetailTourReview.jsx
  src/components/DetailPage/DetailTourTitle/DetailTourTitle.jsx
  src/components/DetailPage/DetailTourTripInfo/DetailTourTripInfo.jsx
  src/components/Landing/Carousel.jsx
  src/components/Landing/GoodsSection.jsx
  src/components/Landing/Landing.jsx
  src/components/Landing/MainButtonSection.jsx
  src/components/Landing/MainIconSection.jsx
  src/components/Landing/TrendPlace.jsx
  src/components/Landing/TrendPlaceSection.jsx
  src/components/common/Button.jsx
  src/components/common/Footer.jsx
  src/components/common/Header.jsx
  src/components/common/Layout.jsx
  src/components/layout/atom/DivideLine.jsx
  src/components/layout/atom/Flex.jsx
  src/pages/DetailTour.jsx
  src/pages/Landing/index.jsx
Labels: feature

#63 [TourLisy] 바텀 시트 추가+ 코드 리펙토링
  package-lock.json
  package.json
  public/assets/icon/ic_cancel.png
  public/assets/icon/ic_reset.png
  src/App.jsx
  src/components/TourList/BottomSheet/BottomSheet.jsx
  src/components/TourList/BottomSheet/BsPrice.jsx
  src/components/TourList/BottomSheet/BsSelectCalendar.jsx
  src/components/TourList/BottomSheet/BsTourType.jsx
  src/components/TourList/BottomSheet/index.js
  src/components/TourList/TourListCardSquare.jsx
  src/components/TourList/TourListHeaderSection/TourListHeaderSection.jsx
  src/components/TourList/TourListHeaderSection/index.js
  src/components/TourList/TourListItemSection/TourListItemSection.jsx
  src/components/TourList/TourListItemSection/index.js
  src/components/TourList/TourListSortNav/TourListSortNav.jsx
  src/components/TourList/TourListSortNav/index.js
  src/components/TourListCardSquare.jsx
  src/components/TourListHeaderSection/TourListHeaderSection.jsx
  src/components/common/Layout.jsx
  src/components/layout/atom/Flex.jsx
  src/pages/TourListPage.jsx
  src/styles/theme.js
  yarn.lock
Labels: feature, refactor

#71 Feature/tourlist page
  package.json
  src/components/TourList/BottomSheet/BottomSheet.jsx
  src/components/TourList/BottomSheet/BsPrice.jsx
  src/components/TourList/BottomSheet/BsSelectCalendar.jsx
  src/components/TourList/TourListCardSquare.jsx
  src/components/TourList/TourListHeaderSection/TourListHeaderSection.jsx
  src/pages/TourListPage.jsx
  yarn.lock
Labels: feature

#75 Update README.md
  README.md
Labels: init

#76 Feature/axios config
  .gitignore
  package.json
  src/api/axios.js
  src/components/Landing/GoodsSection.jsx
  src/components/Landing/index.jsx
  src/components/Tour/Tour.jsx
  src/components/layout/atom/ImgWithSrc.jsx
  vite.config.js
  yarn.lock
Labels: feature

#77 Feature/landing page
  .eslintrc.json
  src/components/Landing/GoodsSection.jsx
  src/components/Landing/IndivGoods.jsx
  src/components/Landing/index.jsx
  src/components/layout/atom/EllipsisText.jsx
  src/components/layout/atom/Icon.jsx
  src/components/layout/atom/ImgWithSrc.jsx
  src/utils/addCommasInNumber.js
Labels: feature

#84 Feature/detail page api 연동
  index.html
  src/components/DetailPage/DetailPageFloat/DetailPageFloat.jsx
  src/components/DetailPage/DetailPageFloat/index.js
  src/components/DetailPage/DetailTour.jsx
  src/components/DetailPage/DetailTourAbout/DetailTourAbout.jsx
  src/components/DetailPage/DetailTourCourse/DetailTourCourse.jsx
  src/components/DetailPage/DetailTourDescription/DetailTourDescription.jsx
  src/components/DetailPage/DetailTourGuide/DetailTourGuide.jsx
  src/components/DetailPage/DetailTourGuide/DetailTourMap.jsx
  src/components/DetailPage/DetailTourImg/DetailTourImg.jsx
  src/components/DetailPage/DetailTourMore/DetailTourMore.jsx
  src/components/DetailPage/DetailTourNotice/DetailTourNotice.jsx
  src/components/DetailPage/DetailTourReview/DetailTourReview.jsx
  src/components/DetailPage/DetailTourTitle/DetailTourTitle.jsx
  src/components/DetailPage/DetailTourTripInfo/DetailTourTripInfo.jsx
  src/components/common/Router.jsx
  src/components/layout/atom/DivideLine.jsx
  src/pages/DetailTour/index.jsx
  src/utils/useDetailTour.jsx
  yarn.lock
Labels: feature

#85 Feature/tour page
  public/assets/img/mymagazine_mockup_1.png
  public/assets/img/mymagazine_mockup_2.png
  src/components/Landing/GlobalGoodsSection.jsx
  src/components/Landing/GoodsSection.jsx
  src/components/Landing/MainButtonSection.jsx
  src/components/Landing/MainIconSection.jsx
  src/components/Landing/ParisGoodsSection.jsx
  src/components/Landing/TrendPlaceSection.jsx
  src/components/Landing/index.jsx
  src/components/Tour/BestReviewTourSection.jsx
  src/components/Tour/Tour.jsx
  src/components/common/Header.jsx
  src/components/common/Layout.jsx
  yarn.lock
Labels: feature

#87 ✨ [feat] 스크랩 post / delete 구현
  src/api/axios.js
  src/components/Landing/IndivGoods.jsx
Labels: feature

#90 detailpage에 random list api import
  src/App.jsx
  src/components/DetailPage/DetailTourAbout/DetailTourAbout.jsx
  src/components/DetailPage/DetailTourCourse/DetailTourCourse.jsx
  src/components/DetailPage/DetailTourGuide/DetailTourMap.jsx
  src/components/DetailPage/DetailTourMore/DetailTourMore.jsx
  src/components/DetailPage/DetailTourMore/MoreTour.jsx
  src/components/DetailPage/DetailTourReview/DetailTourReview.jsx
  src/components/common/Footer.jsx
  src/utils/README.md
  src/utils/useDetailTour.jsx
  vercel.json
Labels: feature

#89 Feature/tour page
  src/components/Landing/IndivGoods.jsx
  src/components/Landing/TrendPlace.jsx
  src/components/Landing/TrendPlaceSection.jsx
  src/components/Landing/index.jsx
  src/components/Tour/Tour.jsx
  src/components/layout/atom/Flex.jsx
Labels: feature

#91 2차 배포 진행합니다
  src/components/DetailPage/DetailTourAbout/DetailTourAbout.jsx
  src/components/DetailPage/DetailTourCourse/DetailTourCourse.jsx
  src/components/DetailPage/DetailTourGuide/DetailTourMap.jsx
  src/components/DetailPage/DetailTourMore/DetailTourMore.jsx
  src/components/DetailPage/DetailTourMore/MoreTour.jsx
  src/components/DetailPage/DetailTourReview/DetailTourReview.jsx
  src/components/Landing/IndivGoods.jsx
  src/components/Landing/TrendPlace.jsx
  src/components/Landing/TrendPlaceSection.jsx
  src/components/Landing/index.jsx
  src/components/Tour/Tour.jsx
  src/components/common/Footer.jsx
  src/components/layout/atom/Flex.jsx
  src/utils/README.md
  src/utils/useDetailTour.jsx
Labels: feature

#92 Feature/detail page
  src/components/DetailPage/DetailPageFloat/DetailPageFloat.jsx
  src/components/DetailPage/DetailTour.jsx
  src/components/DetailPage/DetailTourAbout/DetailTourAbout.jsx
  src/components/DetailPage/DetailTourCourse/DetailTourCourse.jsx
  src/components/DetailPage/DetailTourGuide/DetailTourMap.jsx
  src/components/DetailPage/DetailTourImg/DetailTourImg.jsx
  src/components/DetailPage/DetailTourMore/DetailTourMore.jsx
  src/components/DetailPage/DetailTourMore/MoreTour.jsx
  src/components/DetailPage/DetailTourReview/DetailTourReview.jsx
  src/components/DetailPage/DetailTourTitle/DetailTourTitle.jsx
  src/components/DetailPage/DetailTourTripInfo/DetailTourTripInfo.jsx
Labels: feature, refactor

#93 ✨ [feat] 예약하기 하트 스크랩 기능 추가
  src/components/DetailPage/DetailPageFloat/DetailPageFloat.jsx
Labels: feature

#94 Feature/tourlist fetch
  src/App.jsx
  src/api/tourList.js
  src/api/tourListAxios.jsx
  src/components/DetailPage/DetailTourAbout/DetailTourAbout.jsx
  src/components/DetailPage/DetailTourDescription/DetailTourDescription.jsx
  src/components/DetailPage/DetailTourGuide/DetailTourGuide.jsx
  src/components/DetailPage/DetailTourMore/MoreTour.jsx
  src/components/DetailPage/DetailTourNotice/DetailTourNotice.jsx
  src/components/DetailPage/DetailTourReview/DetailTourReview.jsx
  src/components/DetailPage/DetailTourTitle/DetailTourTitle.jsx
  src/components/DetailPage/DetailTourTripInfo/DetailTourTripInfo.jsx
  src/components/TourList/BottomSheet/BottomSheet.jsx
  src/components/TourList/BottomSheet/BsCalendar.jsx
  src/components/TourList/BottomSheet/BsPrice.jsx
  src/components/TourList/BottomSheet/BsSelectCalendar.jsx
  src/components/TourList/BottomSheet/BsTourType.jsx
  src/components/TourList/TourListCardSquare.jsx
  src/components/TourList/TourListHeaderSection/TourListHeaderSection.jsx
  src/components/TourList/TourListItemSection/TourListItemSection.jsx
  src/components/TourList/TourListSortNav/TourListSortNav.jsx
  src/components/layout/atom/Text.jsx
  src/pages/TourListPage/index.jsx
  src/recoil/tourListRecoil.jsx
Labels: feature

#95 Dev
  src/App.jsx
  src/api/tourList.js
  src/api/tourListAxios.jsx
  src/components/DetailPage/DetailTourDescription/DetailTourDescription.jsx
  src/components/DetailPage/DetailTourGuide/DetailTourGuide.jsx
  src/components/DetailPage/DetailTourMore/MoreTour.jsx
  src/components/DetailPage/DetailTourNotice/DetailTourNotice.jsx
  src/components/DetailPage/DetailTourReview/DetailTourReview.jsx
  src/components/DetailPage/DetailTourTitle/DetailTourTitle.jsx
  src/components/DetailPage/DetailTourTripInfo/DetailTourTripInfo.jsx
  src/components/TourList/BottomSheet/BottomSheet.jsx
  src/components/TourList/BottomSheet/BsCalendar.jsx
  src/components/TourList/BottomSheet/BsPrice.jsx
  src/components/TourList/BottomSheet/BsSelectCalendar.jsx
  src/components/TourList/BottomSheet/BsTourType.jsx
  src/components/TourList/TourListCardSquare.jsx
  src/components/TourList/TourListHeaderSection/TourListHeaderSection.jsx
  src/components/TourList/TourListItemSection/TourListItemSection.jsx
  src/components/TourList/TourListSortNav/TourListSortNav.jsx
  src/components/layout/atom/Text.jsx
  src/pages/TourListPage/index.jsx
  src/recoil/tourListRecoil.jsx
Labels: deploy

#97 Dev
  src/api/tourListAxios.jsx
  src/components/DetailPage/DetailPageFloat/DetailPageFloat.jsx
  src/components/DetailPage/DetailTourMore/MoreTour.jsx
  src/components/DetailPage/DetailTourTitle/DetailTourTitle.jsx
  src/components/DetailPage/DetailTourTripInfo/DetailTourTripInfo.jsx
  src/components/TourList/BottomSheet/BsTourType.jsx
  src/components/TourList/TourListHeaderSection/TourListHeaderSection.jsx
  src/components/TourList/TourListItemSection/TourListItemSection.jsx
Labels: deploy
